# Generated by Django 3.2 on 2024-11-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoDiseñoApp', '0002_auto_20241119_1426'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
