# Generated by Django 3.2 on 2024-11-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoDiseñoApp', '0004_alter_maquinaria_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='mantenimiento_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
