# Generated by Django 3.2 on 2024-11-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoDiseñoApp', '0005_maquinaria_mantenimiento_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquinaria',
            old_name='mantenimiento_info',
            new_name='informacion_mantenimiento',
        ),
    ]
