# Generated by Django 3.2 on 2024-11-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoDiseñoApp', '0006_rename_mantenimiento_info_maquinaria_informacion_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('fecha_rentado', models.DateField()),
                ('fecha_devolucion', models.DateField()),
                ('terms_accepted', models.BooleanField(default=False)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentas', to='ProyectoDiseñoApp.maquinaria')),
            ],
        ),
    ]
